/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form.DeliveryRunner;

import java.util.List;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import Class.RunnerUptStatus;
import java.util.ArrayList;

/**
 *
 * @author User
 */
public class Runner_UpdateTask extends javax.swing.JFrame {

    private RunnerUptStatus runnerUptStatus;
    private String username;
    private String runnerID;

    /**
     * Creates new form Runner_UpdateTask
     */
    public Runner_UpdateTask(String username) {
        initComponents();
        runnerUptStatus = new RunnerUptStatus();
        runnerID = (runnerUptStatus.getRunnerUserIdByUsername(username));
        displayTaskStatus(runnerUptStatus.getRunnerUserIdByUsername(username));
    }

    private void displayTaskStatus(String runnerID) {

        List<List<String>> acceptedOrderDetailsList = runnerUptStatus.getAcceptedOrderDetails(runnerID);

        DefaultTableModel model = (DefaultTableModel) table_taskstatus.getModel();
        model.setRowCount(0); // Clear existing rows in the table

        for (List<String> acceptedOrderDetails : acceptedOrderDetailsList) {
            if (acceptedOrderDetails != null && acceptedOrderDetails.size() >= 8) {
                // Extract individual values from the list
                String OrderID = acceptedOrderDetails.get(0);
                String OrderPlacementTime = acceptedOrderDetails.get(1);
                String OrderItemID = acceptedOrderDetails.get(2);
                String OrderAmount = acceptedOrderDetails.get(3);
                String OrderStatus = acceptedOrderDetails.get(4);
                String CustomerUserID = acceptedOrderDetails.get(5);
                String VendorUserID = acceptedOrderDetails.get(6);

                // Add a row to the table with order details
                model.addRow(acceptedOrderDetails.toArray());
            }
        }
    }

    private void refreshTable(String runnerID) {
        DefaultTableModel model = (DefaultTableModel) table_taskstatus.getModel();
        model.setRowCount(0); // Clear existing rows in the table

        List<List<String>> acceptedOrderDetailsList = runnerUptStatus.getAcceptedOrderDetails(runnerID);

        for (List<String> acceptedOrderDetails : acceptedOrderDetailsList) {
            if (acceptedOrderDetails != null && acceptedOrderDetails.size() >= 8) {
                // Extract individual values from the list
                String OrderID = acceptedOrderDetails.get(0);
                String OrderPlacementTime = acceptedOrderDetails.get(1);
                String OrderItemID = acceptedOrderDetails.get(2);
                String OrderAmount = acceptedOrderDetails.get(3);
                String OrderStatus = acceptedOrderDetails.get(4);
                String CustomerUserID = acceptedOrderDetails.get(5);
                String VendorUserID = acceptedOrderDetails.get(6);

                // Add a row to the table with order details
                model.addRow(acceptedOrderDetails.toArray());
            }
        }

        model.fireTableDataChanged(); // Notify the table that the data has changed
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_taskstatus = new javax.swing.JTable();
        btn_pickup = new javax.swing.JButton();
        btn_delivered = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_taskstatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "OrderID", "OrderPlacementTime", "OrderItemID", "OrderAmount", "OrderStatus", "CustomerUserID", "VendorUserID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_taskstatus.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table_taskstatus);
        if (table_taskstatus.getColumnModel().getColumnCount() > 0) {
            table_taskstatus.getColumnModel().getColumn(0).setResizable(false);
            table_taskstatus.getColumnModel().getColumn(1).setResizable(false);
            table_taskstatus.getColumnModel().getColumn(2).setResizable(false);
            table_taskstatus.getColumnModel().getColumn(3).setResizable(false);
            table_taskstatus.getColumnModel().getColumn(4).setResizable(false);
            table_taskstatus.getColumnModel().getColumn(5).setResizable(false);
            table_taskstatus.getColumnModel().getColumn(6).setResizable(false);
        }

        btn_pickup.setText("PickUp");
        btn_pickup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pickupActionPerformed(evt);
            }
        });

        btn_delivered.setText("Delivered");
        btn_delivered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deliveredActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_pickup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_delivered, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE))
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_pickup)
                .addGap(18, 18, 18)
                .addComponent(btn_delivered)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pickupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pickupActionPerformed
        int selectedRow = table_taskstatus.getSelectedRow();
        if (selectedRow != -1) {
            String orderStatus = (String) table_taskstatus.getValueAt(selectedRow, 4);
            if (orderStatus.equals("Accepted")) {
                String orderID = (String) table_taskstatus.getValueAt(selectedRow, 0); // Assuming OrderID is in the first column

                runnerUptStatus.updateOrderFile(orderID, "Pick-Up");
            }

        }
        refreshTable(runnerID);
    }//GEN-LAST:event_btn_pickupActionPerformed

    private void btn_deliveredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deliveredActionPerformed
        int selectedRow = table_taskstatus.getSelectedRow();
        if (selectedRow != -1) {
            String orderStatus = (String) table_taskstatus.getValueAt(selectedRow, 4);
            if (orderStatus.equals("Pick-Up")) {
                String orderID = (String) table_taskstatus.getValueAt(selectedRow, 0); // Assuming OrderID is in the first column
                int vendorID = Integer.parseInt(runnerUptStatus.getVendorID(orderID));

                runnerUptStatus.updateOrderFile(orderID, "Delivered ");
                
                runnerUptStatus.createCreditTransaction(runnerID, orderID);
                
                runnerUptStatus.updateRunnerandVendorCredit(Integer.parseInt(runnerID), vendorID, true);
            }

        }
        refreshTable(runnerID);
    }//GEN-LAST:event_btn_deliveredActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Runner_UpdateTask.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Runner_UpdateTask.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Runner_UpdateTask.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Runner_UpdateTask.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Runner_UpdateTask("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delivered;
    private javax.swing.JButton btn_pickup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_taskstatus;
    // End of variables declaration//GEN-END:variables
}
